---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
  html_notebook: default
---
c(1,2,3)

rep("Mates",7)

c() # Para definir un vector

scan() #Para definir un vector
  
fix(x) #Para modificar visualmente un vector x

rep(a,n) #Para definir un vector constante que contiene el dato a rpetido n veces


c(2,TRUE,3.5)

c(4,5.67,'Juan Gabriel')

rep(1995,10)
vec <-c(16,0,1,20,1,7,88,5,1,9)
vec
fix(vec)
vec
fix(vec)
vec

vec
fix(vec)


vec

# Progresiones aritmeticas y secuencias

Una progresion aritmeitca es una sucsion de numeros tales que la diferencia, d, de cuaquier par de terminos sucesivos de la secuencia es constante.

                        $\ an = a1 + (n-1) . d$
                        
### Seq(a,b,by=d)

Para generar una progresio aritemitca de diferencia $d$ que empieza en $a$ hasta llegar a $b$

### Seq(a,b,length.out=n)

Define progresion aritmetica de longitud n que va de $a$ a $b$ con diferencia $d$. Por tanto $d=(b-a)/(n-1)$

### Seq(a,by=d,length.out=n)

Define la progresion aritmetica de longitud $n$ y diferencia $d$ que empieza en $a$

### a:b

Define la secuencia de numeros enteros(z) consecutivos entre dos numeros $a$ y $b$

#### Ejemplos

seq(5,60, by=5)

seq(5,60, by=2.5)

seq(5,60, by=3.5)

##### No se pasa del dato

seq(100,6, by=9)

seq(4,35,length.out=7)

seq(4, length.out=5, by=3)

1:10

2:5

-2:5

1:20

seq(2,length.out=20, by=2)

seq(17,length.out=2,by=2)

x <- c(rep(pi,5),5:10,-7)

c(0,x,10,x,20)

# Funciones

Cuando queremos aplicar una funcion a cada uno de los elementos de un vector de datos, la funcion $sapply$ nos ahorra tener que programar con bucles en $R$:

## Sapply(nombre_de_vector, FUN=nombre_de_funcion):

Para aplicar dicha funcion a todos los elementos del vector

## sqrt(x):

Calcula un nuevo vector con las raices cuadradas de cada uno de los elementos vector $x$

### Ejemplos:

x = 1:10
x

x+pi
x*pi
sqrt(x)
2^x
x^2

sapply(x, FUN= function(elemento){sqrt(elemento)})

cd = function(x){summary(lm(1:4)~c(1:3,x))[r.squared] }
cd(4)
cd(5)

(1:10)*(1:10)

1:10 + 1:10

(1:10)^(1:10)

n = 1:100

x = 2*3^(n/2)-15

(1:100)^2/((1:100)^2+1)


Dado un vetor de datos(x) podemos calcular con diversas funciones

### Ejemplos


cuadrado = function(x){x^2}
v = c(1,2,3,4,5,6)
sapply(v,FUN=cuadrado)

sort(v)
rev(v)

rectangulo =function(x){x^3}
x 
sort(x)

rev(x)

s = c(1,2,3,4,5,6,7,8,9)

rev(s)

sort(x)

x = 1:10

length(x)
min(x)
sum(x)
prod(x)
mean(x)
sum(x)/length(x)

cumsum(x)
cummax(x)
cummin(x)
cumprod(x)

diff(x)

diff(cumsum(x))

sort(x)

rev(x)

sort(x, decreasing=TRUE)


