---
title: "Matrices"
author: "DMR"
date: "2/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Matrices

## matrix(vector, nrow=n, byrow=valor_logico)

Para definir una mtriz de $n$ filas formad por las entradas del vector

  - nrow: Numero de filas

  - byrow: si se iguala a $TRUE$, la mtriz se construye por filas; si se iguala a         $FALSE$ (valor por defecto), se construye por columnas. 

  - ncol: Numero de columnas (puede usarse en lugar de nrow)

  - R muestra las matrices indicando como $[i]$ la fila $i-esima$ y $[,j]$ la columna     $j-esima$

  - Todas las entradas de una matriz han de ser del mismo tipo de datos
  
## Ejemplos:

M = matrix(1:12, nrow=4)
M

M = matrix(1:12, nrow=3)
M

M = matrix(1:12, nrow=4, byrow=T)
M

M = matrix(1:12, nrow=5)
M

M = matrix(1, nrow=4, ncol=6)
M

E = matrix(0,nrow=3,ncol=5)
E

vec = c(1,2,3,4,5,6,7,8,9,10,11,12)
vec

V = matrix((vec),nrow=3,ncol=4)
V

## Como constriurlas

  - rbind(vector1,vector2,...): Construye la matriz de filas vector1, vector2, ....
  
  - cbind(vector1, vector2,...): Construye la matriz de columnas vector1, vector2, ...
    
    - Los vectores han de tener la misma longitud
    
    -Tambien  sirve para anadir columnas(filas) a una matriz o concatenar por             columnas(filas) matrices con el mismo numero de filas (columnas)
    
  -diag(vector): Para construir una matriz diagonal con un vector dado
  
    - Si aplicamos diag a un numero $n$, produce una matriz identidad de orden $n$
    
### Ejemplos:

M

rbind(M, c(1,2,3), c(-1,-2,-3))

cbind(M, c(1,2,3), c(-1,-2,-3))

diag(c(1,2,3,4))

## Submatrices

- matriz[i,j]: Indica la entrada $(i,j)$ de la matriz, siendo $i,j E N$.Si $i$ y $j$ son vectores de indices, estaremos definiendo la submatriz con las filas pertenecientes al vector i y columnas pertenecientes al vector j

- matriz[i,]: Indica la fila $i-esima$ de la matriz, siendo $ i E n$

  -Si $i(j)$ es un vector de indices, estaremos definiendo la submatriz con las filas     (columnas) pertenecientes al vector $i(j)$
  
### Ejemplos:

M[2,3]

M[2,]

M[,3]

M[c(2,3,5), 1:2]


## Funciones

diag(M)

nrow(M)

ncol(M)

dim(M)

sum(M)

prod(M)

mean()
