---
title: "Graficos"
author: "DMR"
date: "2/13/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Graficos con la funcion `plot`

## Graficos basico de puntos

- plot(x,y): para dibujar un grafico de puntos siendo $x,y$ vectores numericos

alumnos = c(1:10)

notas = c(2,5,7,9,8,3,5,6,10,7)

plot(alumnos,notas)

```{r primer_plot, fig.cap='Grafico basico explicando el uso de plot',fig.align='center'}
x = c(2,6,4,9,-1)
y = c(1,8,4,-2,4)
plot(x,y)

```
Si no incorporamos vector `y`, `R` nos va a tomar el parametro `x` como si fuese el vector de datos `y`: `plot(1:n,x)`

```{r}
plot(2^(1:6))
```
Si queremos represntar una funcion $f(x)$

```{r}
f <- function(x){sqrt(x)}
plot(f)
```

## Parametros de la funcion plot()

```{r, echo=FALSE, fig.align='center'}
n = 1:20
fib = (1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n
fib
par(mfrow = c(1,2))
plot(fib,  xlab="n", ylab = expression(F[n]),
     main = "Sucesion de Fibonacci",pch=21, cex=2,col="powderblue",bg="orchid",log = "xy")

plot(fib,  xlab="n", ylab = expression(F[n]),
     main = "Sucesion de Fibonacci",pch=21, cex=2,col="powderblue",bg="orchid",log = "xy")
par(mfrow=c(1,1))

```

## Parametros de la funcion plot()
### 2

```{r}
plot(n, fib,pch = 21, col= "red", bg="yellow", cex=1.2, 
     type="o", lty = "dashed", lwd = 1.5, xlim = c(1,10), 
     ylim = c(1,100), xaxp = c(1,10,3), yaxp = c(1,100,10))
```
```{r}
f <- function(x){
  x^2 -2*x + sqrt(abs(x))
}
plot(f, xlim=(c(-3,3)), points(0,0,pch=19))
```

